"""add table

Revision ID: 7dbfa81d9d4a
Revises: dc64e5581e3d
Create Date: 2024-09-04 18:06:30.572606

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7dbfa81d9d4a"
down_revision: Union[str, None] = "dc64e5581e3d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jwtokens",
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("issued_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column(
            "token_type",
            sa.Enum("ACCESS", "REFRESH", name="tokentypeenum"),
            nullable=False,
        ),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["userts.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    # op.alter_column(
    #     "emails",
    #     "user_id",
    #     existing_type=sa.NUMERIC(),
    #     type_=sa.UUID(),
    #     existing_nullable=False,
    # )
    # op.alter_column(
    #     "emails",
    #     "id",
    #     existing_type=sa.NUMERIC(),
    #     type_=sa.UUID(),
    #     existing_nullable=False,
    # )
    # op.alter_column(
    #     "phonenumbers",
    #     "id",
    #     existing_type=sa.NUMERIC(),
    #     type_=sa.UUID(),
    #     existing_nullable=False,
    # )
    # op.alter_column(
    #     "smscodes",
    #     "phone_number_id",
    #     existing_type=sa.NUMERIC(),
    #     type_=sa.UUID(),
    #     existing_nullable=False,
    # )
    # op.alter_column(
    #     "smscodes",
    #     "id",
    #     existing_type=sa.NUMERIC(),
    #     type_=sa.UUID(),
    #     existing_nullable=False,
    # )
    # op.alter_column(
    #     "socialaccounts",
    #     "user_id",
    #     existing_type=sa.NUMERIC(),
    #     type_=sa.UUID(),
    #     existing_nullable=True,
    # )
    # op.alter_column(
    #     "socialaccounts",
    #     "id",
    #     existing_type=sa.NUMERIC(),
    #     type_=sa.UUID(),
    #     existing_nullable=False,
    # )
    # op.alter_column(
    #     "users",
    #     "id",
    #     existing_type=sa.NUMERIC(),
    #     type_=sa.UUID(),
    #     existing_nullable=False,
    # )
    # op.alter_column(
    #     "userts",
    #     "client_uuid",
    #     existing_type=sa.NUMERIC(),
    #     type_=sa.UUID(),
    #     existing_nullable=True,
    # )
    # op.alter_column(
    #     "userts",
    #     "phone_number_id",
    #     existing_type=sa.NUMERIC(),
    #     type_=sa.UUID(),
    #     existing_nullable=False,
    # )
    # op.alter_column(
    #     "userts",
    #     "id",
    #     existing_type=sa.NUMERIC(),
    #     type_=sa.UUID(),
    #     existing_nullable=False,
    # )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "userts",
        "id",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=False,
    )
    op.alter_column(
        "userts",
        "phone_number_id",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=False,
    )
    op.alter_column(
        "userts",
        "client_uuid",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "id",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=False,
    )
    op.alter_column(
        "socialaccounts",
        "id",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=False,
    )
    op.alter_column(
        "socialaccounts",
        "user_id",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=True,
    )
    op.alter_column(
        "smscodes",
        "id",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=False,
    )
    op.alter_column(
        "smscodes",
        "phone_number_id",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=False,
    )
    op.alter_column(
        "phonenumbers",
        "id",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=False,
    )
    op.alter_column(
        "emails",
        "id",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=False,
    )
    op.alter_column(
        "emails",
        "user_id",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=False,
    )
    op.drop_table("jwtokens")
    # ### end Alembic commands ###
