"""add tabl smscodes

Revision ID: 0ff7d8dd0b95
Revises: dfbcdc67f809
Create Date: 2024-09-04 16:41:13.182613

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0ff7d8dd0b95"
down_revision: Union[str, None] = "dfbcdc67f809"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "smscodes",
        sa.Column("code", sa.String(length=6), nullable=False),
        sa.Column("is_used", sa.Boolean(), nullable=False),
        sa.Column("phone_number_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["phone_number_id"],
            ["phonenumbers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # op.alter_column(
    #     "emails",
    #     "user_id",
    #     existing_type=sa.NUMERIC(),
    #     type_=sa.UUID(),
    #     existing_nullable=False,
    # )
    # op.alter_column(
    #     "emails",
    #     "id",
    #     existing_type=sa.NUMERIC(),
    #     type_=sa.UUID(),
    #     existing_nullable=False,
    # )
    # op.alter_column(
    #     "phonenumbers",
    #     "id",
    #     existing_type=sa.NUMERIC(),
    #     type_=sa.UUID(),
    #     existing_nullable=False,
    # )
    # op.alter_column(
    #     "users",
    #     "id",
    #     existing_type=sa.NUMERIC(),
    #     type_=sa.UUID(),
    #     existing_nullable=False,
    # )
    # op.alter_column(
    #     "userts",
    #     "client_uuid",
    #     existing_type=sa.NUMERIC(),
    #     type_=sa.UUID(),
    #     existing_nullable=True,
    # )
    # op.alter_column(
    #     "userts",
    #     "phone_number_id",
    #     existing_type=sa.NUMERIC(),
    #     type_=sa.UUID(),
    #     existing_nullable=False,
    # )
    # op.alter_column(
    #     "userts",
    #     "id",
    #     existing_type=sa.NUMERIC(),
    #     type_=sa.UUID(),
    #     existing_nullable=False,
    # )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "userts",
        "id",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=False,
    )
    op.alter_column(
        "userts",
        "phone_number_id",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=False,
    )
    op.alter_column(
        "userts",
        "client_uuid",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "id",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=False,
    )
    op.alter_column(
        "phonenumbers",
        "id",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=False,
    )
    op.alter_column(
        "emails",
        "id",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=False,
    )
    op.alter_column(
        "emails",
        "user_id",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=False,
    )
    op.drop_table("smscodes")
    # ### end Alembic commands ###
